### PR TITLE
Upgrading to Netty 4.1 and reintroducing proxy support

### PR DESCRIPTION
**Pull request by randak**
Rebased. See #40 for original PR

### CODE REVIEW

**Comment by randak** [comment]
@erwan The tests have passed! Thanks for fixing those.

**Comment by erwan** [comment]
OK, I just tested with a Play app and they're still on Netty 4.0, that causes conflicts :-/

Since we have many users using Play Framework we might hold off on that until Play migrates to Netty 4.1, or provide an alternative server that works out-of-the-box.

**Comment by randak** [comment]
What version of Play? We're using Play with this code on our production sites and not having any issues.

**Comment by randak** [comment]
@erwan Hey—could you provide more information on what wasn't working? As mentioned, this is working with Play just fine for us. We're running 2.4, which is using Netty 4.0, and there are not any conflicts.

**Comment by randak** [comment]
Hey @erwan, would really love to get these changes merged. Could you provide some more context on what didn't work, please? We have had no compatibility issues in our environment.

**Comment by randak** [comment]
So based on what I'm reading [here](http://stackoverflow.com/questions/35827782/conflict-between-play-framework-2-5-and-grpc-0-13), it sounds like this works for 2.4 but not 2.5. We're still running 2.4 so I'm assuming you're not.

**Comment by Katyucha** [comment]
What about this PR ?? Need it too :)

**Comment by randak** [comment]
@Katyucha If you're using Play 2.4 (or lower, I assume), you can do what we are doing and point your project to this forked version. It is incompatible with Play 2.5 due to dependency overrides on Netty 4.0 vs. 4.1. 

We packaged this version with a special version number and put it in our own Maven repository.

**Comment by Katyucha** [comment]
I have problems on play 2.4.6 and I use your PR with success

**Comment by randak** [comment]
This is no longer relevant to me, since I don't work on a Prismic-based site anymore. I'm closing this, anyone else should feel free to take it over if they need this.

**Pull request closed without merging**
